name: GitHub Actions
on: [push]
jobs:
  Run-Backend-and-Frontend:
    runs-on: ubuntu-latest
    strategy:
      node-version [10.x, 12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies for client
        run: npm install

      - name: Run react app
        run: npm start